#!/usr/bin/env ruby

require_relative './helper.rb'

# Index topics
class Indexer
  include ScrapperHelper
  def run
    index = index_init('MXM0JWJNIW',
                       '9ef50a76fe1c2522c37204ae1d5e12ea',
                       'smashingmagazine_posts')

    settings = {
      distinct: true,
      highlightPostTag: '</span>',
      highlightPreTag: '<span class="search-hit--highlight">',
      ignorePlurals: true,
      removeWordsIfNoResults: 'allOptional',
      attributeForDistinct: 'url',
      attributesForFaceting: %w(type tags section),
      attributesToIndex: %w(
        title
        type
        section
        tags
        author
        description
      ),
      attributesToRetrieve: %w(
        url
        title
        type
        description_short
        tags
        section
        image
        author
        comment_count
        published_date
      ),
      customRanking: [
        'desc(published_date)', 
        'desc(modified_date)',
        'desc(comment_count)',
        'desc(priority)'
      ],
      slaves: [
        'smashingmagazine_posts_published_date_desc',
        'smashingmagazine_posts_comment_count_asc'
      ]
    }
    index.set_settings(settings);

    # Slaves are manually configured

    index_json(Dir['./json/articles/*.json'], index)
  end
end
Indexer.new.run
