#!/usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'
require_relative '../lib/helper_sitemap'
require_relative '../lib/helper_download'

# Download on disk all the url defined in the specified sitemaps
sitemaps = [
  './data/sitemaps/post-sitemap1.xml',
  './data/sitemaps/post-sitemap2.xml',
  './data/sitemaps/post-sitemap3.xml'
]
urls = HelperSitemap.get_urls(*sitemaps)
HelperDownload.download(urls)
