#!/usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'
require 'algoliasearch'

root_dir = File.expand_path(File.join(File.dirname(__FILE__), '..'))
app_id = 'KHKP14DMQR'
api_key = File.read(File.join(root_dir,'_algolia_api_key')).chomp
index_name = 'smashingmagazine'

Algolia.init(application_id: app_id, api_key: api_key)
index = Algolia::Index.new(index_name)

record_file = File.join(root_dir, 'data', 'records.json')
records = JSON.parse(File.read(record_file))

records.each_slice(500).with_index do |batch, i|
  puts "  Pushing batch #{i}"
  index.add_objects(batch.to_a)
end
