#!/usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'
require_relative '../lib/helper_extract'
require_relative '../lib/helper_push'

records = HelperExtract.all_records
app_id = 'MXM0JWJNIW'
index = 'smashingmagazine'
index_tmp = 'smashingmagazine_tmp'
slave_comment_asc = 'smashingmagazine_comment_count_asc'
slave_comment_desc = 'smashingmagazine_comment_count_desc'
slave_date_desc = 'smashingmagazine_published_date_desc'
slaves = [slave_comment_asc, slave_comment_desc, slave_date_desc]

settings = {
  attributesToIndex: [
    'title',
    'unordered(description)',
    'tags',
    'author'
  ],
  customRanking: [
    'desc(publishedDate)',
    'desc(commentCount)'
  ],
  attributesForFacetting: [
    'tags'
  ],
  highlightPreTag: '<span class="search-hit--highlight">',
  highlightPostTag: '</span>'
}
default_ranking = %w(typo geo words filters proximity attribute exact custom)

settings_slave_comment_asc = settings.merge(
  ranking: ['asc(commentCount)'] + default_ranking
)
settings_slave_comment_desc = settings.merge(
  ranking: ['desc(commentCount)'] + default_ranking
)
settings_slave_date_desc = settings.merge(
  ranking: ['desc(publishedDate)'] + default_ranking
)

HelperPush.new(app_id)
   .set_settings(index_tmp, settings)
   .push_records(index_tmp, records)
   .move_index(index_tmp, index)
   .add_slaves(index, slaves)
   .set_settings(slave_comment_asc, settings_slave_comment_asc)
   .set_settings(slave_comment_desc, settings_slave_comment_desc)
   .set_settings(slave_date_desc, settings_slave_date_desc)
