#!/usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'
require 'algoliasearch'

root_dir = File.expand_path(File.join(File.dirname(__FILE__), '..'))
app_id = 'KHKP14DMQR'
api_key = File.read(File.join(root_dir,'_algolia_api_key')).chomp
index_name = 'smashingmagazine'

Algolia.init(application_id: app_id, api_key: api_key)
index = Algolia::Index.new(index_name)

settings = {
  attributesToIndex: [
    'title',
    'unordered(tags.name)',
    'unordered(description)',
    'author'
  ],
  customRanking: [
    'desc(publishedDate)',
    'desc(commentCount)'
  ],
  attributesForFacetting: [
    'tags.name'
  ],
  highlightPreTag: '<span class="search-hit--highlight">',
  highlightPostTag: '</span>',
  ignorePlurals: true,
  removeWordsIfNoResults: 'allOptional'
}

index.set_settings(settings)
puts "Settings set"
