#!/usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'
require 'algoliasearch'

app_id = 'XXXXXX' # Replace with your APP_ID
root_dir = File.expand_path(File.join(File.dirname(__FILE__), '..'))
api_key = File.read(File.join(root_dir,'_algolia_api_key')).chomp
index_name = 'smashingmagazine'

Algolia.init(application_id: app_id, api_key: api_key)
index = Algolia::Index.new(index_name)

settings = {
  attributesToIndex: [
    'title',
    'unordered(tags.name)',
    'unordered(description)',
    'author'
  ],
  customRanking: [
    'desc(publishedDate)',
    'desc(commentCount)'
  ],
  attributesForFacetting: [
    'tags.name'
  ],
  highlightPreTag: '<span class="search-hit--highlight">',
  highlightPostTag: '</span>',
  ignorePlurals: true,
  removeWordsIfNoResults: 'allOptional'
}

index.set_settings(settings)
puts "Settings set"


# The following code is for configuring the replicas needed for the ordering by
# date
default_ranking = %w(typo geo words filters proximity attribute exact)
replica_comment_desc = 'smashingmagazine_comment_count_desc'
settings_replica_comment_desc = settings.merge(
  ranking: ['desc(commentCount)'] + default_ranking
)
replica_date_desc = 'smashingmagazine_published_date_desc'
settings_replica_date_desc = settings.merge(
  ranking: ['desc(publishedDate)'] + default_ranking
)
replicas = [replica_comment_desc, replica_date_desc]

index.set_settings(replicas: replicas)
index.set_settings(replica_comment_desc, settings_replica_comment_desc)
index.set_settings(replica_date_desc, settings_replica_date_desc)
